version: 2
registries:
  npm-registry-iadvize-jfrog-io-iadvize-api-npm-iadvize-npm:
    type: npm-registry
    url: https://iadvize.jfrog.io/iadvize/api/npm/iadvize-npm
    username: "${{secrets.NPM_REGISTRY_IADVIZE_JFROG_IO_IADVIZE_API_NPM_IADVIZE_NPM_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_IADVIZE_JFROG_IO_IADVIZE_API_NPM_IADVIZE_NPM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/packages/eslint-config"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/Paris
  pull-request-branch-name:
    separator: "-"
  labels:
  - "Action: no bump"
  - packages/eslint-config
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-tsdoc
    versions:
    - 0.2.12
    - 0.2.14
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.2
    - 4.16.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.0
  - dependency-name: typescript
    versions:
    - 4.1.4
  commit-message:
    prefix: misc
  rebase-strategy: disabled
  registries:
  - npm-registry-iadvize-jfrog-io-iadvize-api-npm-iadvize-npm
- package-ecosystem: npm
  directory: "/packages/eslint-config-jest"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/Paris
  pull-request-branch-name:
    separator: "-"
  labels:
  - "Action: no bump"
  - packages/eslint-config-jest
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.4
    - 24.1.6
    - 24.1.7
    - 24.3.0
    - 24.3.3
  commit-message:
    prefix: misc
  rebase-strategy: disabled
  registries:
  - npm-registry-iadvize-jfrog-io-iadvize-api-npm-iadvize-npm
- package-ecosystem: npm
  directory: "/packages/eslint-config-mocha"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/Paris
  pull-request-branch-name:
    separator: "-"
  labels:
  - "Action: no bump"
  - packages/eslint-config-mocha
  versioning-strategy: increase
  commit-message:
    prefix: misc
  rebase-strategy: disabled
  registries:
  - npm-registry-iadvize-jfrog-io-iadvize-api-npm-iadvize-npm
- package-ecosystem: npm
  directory: "/packages/eslint-config-redux-saga"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/Paris
  pull-request-branch-name:
    separator: "-"
  labels:
  - "Action: no bump"
  - packages/eslint-config-redux-saga
  versioning-strategy: increase
  commit-message:
    prefix: misc
  rebase-strategy: disabled
  registries:
  - npm-registry-iadvize-jfrog-io-iadvize-api-npm-iadvize-npm
- package-ecosystem: npm
  directory: "/packages/eslint-config-storybook"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/Paris
  pull-request-branch-name:
    separator: "-"
  labels:
  - "Action: no bump"
  - packages/eslint-config-storybook
  versioning-strategy: increase
  commit-message:
    prefix: misc
  rebase-strategy: disabled
  registries:
  - npm-registry-iadvize-jfrog-io-iadvize-api-npm-iadvize-npm
