name: Pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assignee:
    name: 'check assignee'
    runs-on: ubuntu-18.04

    steps:
    - name: Check if there is at least one assignee
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: pull } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });

          if (pull.assignees.length > 0) {
            return;
          }

          throw new Error('Should have at least one assignee');

  create-labels-from-files:
    name: 'create labels from files'
    runs-on: ubuntu-18.04

    steps:
    - name: Create labels from files
      id: version
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: files } = await github.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            per_page: 100,
          });

          const labelSet = files.reduce(
            (labels, file) => {
              const filePath = file.filename;

              const maybeMatch = /packages\/([\w.\-_]*)\/.*/.exec(filePath);

              if (!maybeMatch) {
                return labels;
              }

              const [, packageName] = maybeMatch;

              const label = `packages/${packageName}`;

              labels.add(label);

              return labels;
            },
            new Set([]),
          );

          if (labelSet.size === 0) {
            console.log(`::debug ::No labels extracted from files`);
            return;
          }

          const labels = Array.from(labelSet);

          await github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            labels,
          });

  check-labels-changelog:
    name: 'check labels and changelog'
    runs-on: ubuntu-18.04

    needs:
      - create-labels-from-files

    steps:
    - name: Check if version label is present
      id: version
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const versionLabels = [
            'no-release',
            'patch',
            'minor',
            'major',
          ];

          const { data: labels } = await github.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            per_page: 100,
          });

          const versionLabelsPresent = labels
            .map(label => label.name)
            .filter(name => versionLabels.includes(name));

          if (versionLabelsPresent.length === 1) {
            console.log(`::set-output name=label::${versionLabelsPresent[0]}`)
            return;
          }

          console.log(`::debug ::${versionLabelsPresent.length} matching labels`);

          throw new Error('Should have one and only one of no-release, patch, minor, major labels');

    - name: Check if package label is present
      id: package-label
      if: steps.version.outputs.label != 'no-release'
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: pullLabels } = await github.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            per_page: 100,
          });

          const labels = pullLabels.map(label => label.name);

          const packageLabels = labels.filter(name => name.includes('packages/'));

          console.log(`::debug ::${packageLabels.length} matching labels`);

          if (packageLabels.length !== 1) {
            throw new Error('Pull request should have only one package label');
          }

          console.log(`::set-output name=label::${packageLabels[0]}`)

    - name: Fail if no changelog change when needed
      if: steps.version.outputs.label != 'no-release'
      uses: actions/github-script@0.4.0
      env:
        PACKAGE: ${{ steps.package-label.outputs.label }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: files } = await github.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            per_page: 100,
          });

          const changelogFile = `${process.env.PACKAGE}/CHANGELOG.md`;

          const fileNotDeletedNames = files
            .filter(file => file.status === 'added' || file.status === 'modified')
            .map(file => file.filename);

          if (!fileNotDeletedNames.includes(changelogFile)) {
            throw new Error('Package CHANGELOG.md Unreleased section shoud have line additions when PR is not a no-release')
          }
